<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $titulo ?></title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>

    <nav class="blue">
        <ul>
            <li><a href="http://localhost:8081/KumbiaPHP/alumnos">Alumnnos</a></li>
            <li><a href="http://localhost:8081/KumbiaPHP/profesores/historial">Desarrollo De Software</a></li>
            <li><a href="http://localhost:8081/KumbiaPHP/alumnos/registro">Registro</a></li>
            <li><a href="http://localhost:8081/KumbiaPHP/profesores">Profesores</a></li>
            <li><a href="http://localhost:8081/KumbiaPHP/profesores/historial">Historial profesores</a></li>
        </ul>
    </nav>

    <div class="container">
        <?php 
        
        View::partial('fecha');
        View::content()
        
        ?>
    </div>
    

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>